In [16]:
#1 задача
import numpy as np
a = np.random.random((10, 3))
print (a)
l=(np.abs(a-0.5)).argmin(axis=1)
print (l)
for i in range(len(a)):
    print(a[i][l[i]])

[[0.26035925 0.97711905 0.86069281]
 [0.12769379 0.60917454 0.53622503]
 [0.62863142 0.5079635  0.95444621]
 [0.65259322 0.03694813 0.38528716]
 [0.43139654 0.46089327 0.72776323]
 [0.0339968  0.17912405 0.44381776]
 [0.59420133 0.26392519 0.17528304]
 [0.14952222 0.22830792 0.27379544]
 [0.26804367 0.95179394 0.60523247]
 [0.77737116 0.24048156 0.99232242]]
[0 2 1 2 1 2 0 2 2 1]
0.2603592486374682
0.5362250338091195
0.50796350256858
0.38528715778525646
0.4608932724340826
0.4438177649937104
0.5942013318517932
0.2737954443858279
0.6052324655580024
0.24048155547784378


In [15]:
#2 задача
import numpy as np
a = np.random.random((6, 6))
print (a);
b = a.min(axis=0)
print (b);
c = sum(a.T)
print (c);
c / b
print (c / b)

[[0.58920281 0.12686138 0.32421232 0.52341664 0.06964786 0.07062735]
 [0.23802316 0.90802801 0.97690347 0.60542261 0.74842795 0.15289269]
 [0.85611649 0.83099045 0.68826444 0.45236475 0.81357548 0.05258585]
 [0.6849887  0.24408423 0.16069601 0.80156456 0.9876367  0.36641425]
 [0.50899659 0.46826105 0.03338712 0.79276013 0.02465149 0.15284457]
 [0.32657018 0.71888795 0.82568148 0.18293    0.21579044 0.08181756]]
[0.23802316 0.12686138 0.03338712 0.18293    0.02465149 0.05258585]
[1.70396836 3.6296979  3.69389746 3.24538444 1.98090096 2.3516776 ]
[  7.15883421  28.61152769 110.63839518  17.7411275   80.35622845
  44.72073048]


In [13]:
#3 задача
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x == 0
print (x[1:][zero[:-1]].max())

5


In [14]:
#4 задача
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x == 0
print (x[1:][zero[:-1]].max())

x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for index in range(len(x)):
    n = np.sum(i==index)
    x[index]+=n
print (x)

5
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [ ]:
#5 задача у меня не получилась
from scipy.spatial.distance import cdist
import numpy
def centroid(*cluster):
    x_coords = [p[0] for p in points]
    y_coords = [p[1] for p in points]
    _len = len(points)
    centroid_x = sum(x_coords)/_len
    centroid_y = sum(y_coords)/_len
    return [centroid_x, centroid_y]
def kmeans( obs, k_or_guess, iters = 1000, thresh = 1 ):
    if ( type(k_or_guess) is int ):
        ind = np.arange(len(obs))
        np.random.shuffle(ind)
        rind = ind[:k_or_guess]
        centres = x[rind]
    else:
        centres = np.array( k_or_guess )
    i=0
    while (i<iters and abs(cdist(x[centroids_new], x[centroids_old], 'euclidean'))<thresh):
        centroids_old = centres
        centroids_new = centroid(x[])